# Copyright © 2025 Adventures of the Persistently Impaired (and Other Tales) Limited. All Rights Reserved.
# Docker Compose for PCB Design Agent with nginx reverse proxy
version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8080:80"  # Alternative port for compatibility
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - web
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - app-network

  # Python Backend API
  backend:
    build:
      context: .
      target: production
    environment:
      - PYTHONPATH=/app
      - NODE_ENV=production
    volumes:
      - ./outputs:/app/outputs
      - ./projects:/app/projects
      - ./datasheet_cache:/app/datasheet_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: python -m uvicorn api_server:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    networks:
      - app-network

  # Next.js Web Interface
  web:
    build:
      context: ./web
      dockerfile: ../Dockerfile.web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api  # Use relative URL since nginx handles routing
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: npm start -- --port 3000 --hostname 0.0.0.0
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  outputs:
  projects:
  datasheet_cache: